Repository swcarpentry/r-novice-inflammation, pull requests merged in 2018-06, with the labels that each got.

#368 Include links.md in all episodes
  _episodes/01-starting-with-data.md
  _episodes/02-func-R.md
  _episodes/03-loops-R.md
  _episodes/04-cond.md
  _episodes/05-cmdline.md
  _episodes/06-best-practices-R.md
  _episodes/07-knitr-R.md
  _episodes/08-making-packages-R.md
  _episodes/09-supp-intro-rstudio.md
  _episodes/10-supp-addressing-data.md
  _episodes/11-supp-read-write-csv.md
  _episodes/12-supp-factors.md
  _episodes/13-supp-data-structures.md
  _episodes/14-supp-call-stack.md
  _episodes/15-supp-loops-in-depth.md
  _episodes_rmd/01-starting-with-data.Rmd
  _episodes_rmd/02-func-R.Rmd
  _episodes_rmd/03-loops-R.Rmd
  _episodes_rmd/04-cond.Rmd
  _episodes_rmd/05-cmdline.Rmd
  _episodes_rmd/06-best-practices-R.Rmd
  _episodes_rmd/07-knitr-R.Rmd
  _episodes_rmd/08-making-packages-R.Rmd
  _episodes_rmd/09-supp-intro-rstudio.Rmd
  _episodes_rmd/10-supp-addressing-data.Rmd
  _episodes_rmd/11-supp-read-write-csv.Rmd
  _episodes_rmd/12-supp-factors.Rmd
  _episodes_rmd/13-supp-data-structures.Rmd
  _episodes_rmd/14-supp-call-stack.Rmd
  _episodes_rmd/15-supp-loops-in-depth.Rmd
Labels: template-and-tools

#375 Collect lesson link (see #371)
  _episodes_rmd/06-best-practices-R.Rmd
Labels: bug

#362 edit contributing guidelines for clarity
  CONTRIBUTING.md
Labels: enhancement
