Repository swcarpentry/r-novice-inflammation, pull requests merged in 2018-04, with the labels that each got.

#345 Install roxygen2 from CRAN (fixes #326)
  _episodes/08-making-packages-R.md
  _episodes_rmd/08-making-packages-R.Rmd
  _includes/links.md
Labels: bug

#310 fixes issue #217
  _episodes_rmd/05-cmdline.Rmd
  _episodes_rmd/06-best-practices-R.Rmd
  _episodes_rmd/07-knitr-R.Rmd
  _episodes_rmd/08-making-packages-R.Rmd
  _episodes_rmd/09-supp-intro-rstudio.Rmd
  _episodes_rmd/10-supp-addressing-data.Rmd
  _episodes_rmd/11-supp-read-write-csv.Rmd
  _episodes_rmd/13-supp-data-structures.Rmd
  _episodes_rmd/14-supp-call-stack.Rmd
  _episodes_rmd/15-supp-loops-in-depth.Rmd
Labels: enhancement

#337 Introduce regex with digits instead of wildcard
  _episodes_rmd/03-loops-R.Rmd
Labels: enhancement, regex
