Repository swcarpentry/r-novice-inflammation, pull requests merged in 2018-05, with the labels that each got.

#353 Harmonize whitespace & reformat code to RStudio's style
  _episodes/01-starting-with-data.md
  _episodes/03-loops-R.md
  _episodes/05-cmdline.md
  _episodes/06-best-practices-R.md
  _episodes/10-supp-addressing-data.md
  _episodes/11-supp-read-write-csv.md
  _episodes/12-supp-factors.md
  _episodes/13-supp-data-structures.md
  _episodes/15-supp-loops-in-depth.md
  _episodes_rmd/01-starting-with-data.Rmd
  _episodes_rmd/03-loops-R.Rmd
  _episodes_rmd/05-cmdline.Rmd
  _episodes_rmd/06-best-practices-R.Rmd
  _episodes_rmd/08-making-packages-R.Rmd
  _episodes_rmd/10-supp-addressing-data.Rmd
  _episodes_rmd/11-supp-read-write-csv.Rmd
  _episodes_rmd/12-supp-factors.Rmd
  _episodes_rmd/13-supp-data-structures.Rmd
  _episodes_rmd/15-supp-loops-in-depth.Rmd
Labels: enhancement

#350 Update style to v9.4.0
  CONDUCT.md
  LICENSE.md
  Makefile
  _includes/carpentries.html
  _includes/episode_navbar.html
  _includes/lc/intro.html
  _includes/lc/syllabus.html
  _includes/lesson_footer.html
  _includes/links.md
  _includes/main_title.html
  _includes/navbar.html
  _includes/syllabus.html
  _includes/workshop_footer.html
  _layouts/base.html
  _layouts/workshop.html
  assets/css/bootstrap.css
  assets/css/lesson.scss
  assets/css/syntax.css
  assets/img/lc-icon-black.png
  assets/img/lc-icon-black.svg
  assets/img/swc-icon-blue.svg
  assets/img/swc-logo-blue.svg
  assets/img/swc-logo-white.svg
  bin/chunk-options.R
  bin/extract_figures.py
  bin/generate_md_episodes.R
  bin/lesson_check.py
  bin/lesson_initialize.py
  bin/repo_check.py
  bin/workshop_check.py
Labels: template-and-tools

#359 Repair edit & improve links
  _episodes/01-starting-with-data.md
  _episodes/02-func-R.md
  _episodes/03-loops-R.md
  _episodes/04-cond.md
  _episodes/05-cmdline.md
  _episodes/06-best-practices-R.md
  _episodes/07-knitr-R.md
  _episodes/08-making-packages-R.md
  _episodes/09-supp-intro-rstudio.md
  _episodes/10-supp-addressing-data.md
  _episodes/11-supp-read-write-csv.md
  _episodes/12-supp-factors.md
  _episodes/14-supp-call-stack.md
  _episodes/15-supp-loops-in-depth.md
  _episodes_rmd/01-starting-with-data.Rmd
  _episodes_rmd/02-func-R.Rmd
  _episodes_rmd/03-loops-R.Rmd
  _episodes_rmd/04-cond.Rmd
  _episodes_rmd/05-cmdline.Rmd
  _episodes_rmd/06-best-practices-R.Rmd
  _episodes_rmd/07-knitr-R.Rmd
  _episodes_rmd/08-making-packages-R.Rmd
  _episodes_rmd/09-supp-intro-rstudio.Rmd
  _episodes_rmd/10-supp-addressing-data.Rmd
  _episodes_rmd/11-supp-read-write-csv.Rmd
  _episodes_rmd/12-supp-factors.Rmd
  _episodes_rmd/14-supp-call-stack.Rmd
  _episodes_rmd/15-supp-loops-in-depth.Rmd
Labels: bug

#355 Fix typo & rephrase for clarity
  _episodes/03-loops-R.md
  _episodes_rmd/03-loops-R.Rmd
Labels: enhancement
